# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea2ff62580ce97d85b79d3bd8e06c6ab20cf6afb3ff3be9fd6ae102b75e0460b734c900ab74156e3ebbf610e942492e1f553eaeb44ccb2d6097ff19fa88c4ac1

test:
  secret_key_base: c6493aaf6275ff0b6699003c9b831d0981a5afe782e1ce9aca64e54f0229c9227812274ff05cfbcbe78b55e5cbe676bfd7a144d21015b64d44026e907aac3b48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
